version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vaccine_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vaccineschedule
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234567890
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vaccinescheduleapi:
    build:
      context: .
      dockerfile: VaccineScheduleAPI/Dockerfile
    container_name: vaccine_schedule_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=vaccineschedule;Uid=sa;Pwd=1234567890;"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
